Program("./bin/GestureServer", Glob("./src/*.cpp") + Glob("./src/*.c"),
    CPPPATH=["./include", "../../external/OpenNI/Include"],
    LIBPATH="../../external/OpenNI/Lib/", LIBS="OpenNI")

Program("./bin/MockClient",
        ["./src/MockClient/MockClient.cpp", "./src/vec3.cpp", "./src/tpl.c"],
        CPPPATH=["./include", "../../external/OpenNI/Include"],
        LIBPATH="../../external/OpenNI/Lib/", LIBS="OpenNI")

Program("./bin/MockServer",
        ["./src/MockClient/MockServer.cpp", "./src/vec3.cpp", "./src/tpl.c"],
        CPPPATH=["./include", "../../external/OpenNI/Include"],
        LIBPATH="../../external/OpenNI/Lib/", LIBS="OpenNI")