SharedLibrary("./bin/CameraControl", ["./src/CameraControl.cpp"],
    CPPPATH=[
        "./include",
        "/usr/include/gazebo-4.1",
        "/usr/include/OGRE",
        "/usr/include/OGRE/Terrain",
        "/usr/include/OGRE/Paging",
        "/usr/include/sdformat-2.3"],
    LIBPATH=["/usr/lib/x86_64-linux-gnu/gazebo-4.1/plugins"],
    LIBS=[])